Travis: Build static binaries and deploy them to GH Releases

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -63,6 +63,7 @@ jobs:
       sudo: true
       language: minimal
       compiler: gcc
+      env: ARCH=x86_64
       before_install:
         - "wget 'https://raw.githubusercontent.com/alpinelinux/alpine-chroot-install/v0.6.0/alpine-chroot-install' \
               && echo 'a827a4ba3d0817e7c88bae17fe34e50204983d1e  alpine-chroot-install' | sha1sum -c || exit 1"
@@ -75,25 +76,55 @@ jobs:
         - alpine cmake .
         - alpine make -j2
         - alpine ./check.py
-      env: ARCH=x86_64
 
-    # Build with gcc 6.3 on Alpine Linux (inside chroot) with QEMU emulation.
-    # XXX: We don't run tests, because some fail with QEMU/binfmt and it takes
-    # too long time (hits time limit on Travis).
-    - &test-alpine-no-check
+
+    # Build statically linked release binaries with gcc 6.3 on Alpine Linux
+    # (inside chroot). If building a tagged commit, then deploy release tarball
+    # to GitHub Releases.
+    - &build-alpine
       <<: *test-alpine
+      stage: build
+      env: ARCH=x86_64
       script:
-       - alpine cmake .
-       - alpine make -j2
+        - alpine cmake -DCMAKE_BUILD_TYPE=Release
+                       -DCMAKE_VERBOSE_MAKEFILE=ON
+                       -DCMAKE_CXX_FLAGS="-static -no-pie"
+                       -DCMAKE_C_FLAGS="-static -no-pie" .
+        - alpine make -j2
+        - alpine find bin/ -type f -perm -u=x -exec strip {} +
+        - alpine ls -lh bin/
+        # Check if the built executables are really statically linked.
+        - if [ -n "$(find bin/ -type f -perm -u=x -exec file {} + | grep -Fvw 'statically linked')" ]; then
+              file bin/*; exit 1;
+          fi
+      before_deploy:
+        - PKGNAME="binaryen-$TRAVIS_TAG-$ARCH-linux"
+        - mv bin binaryen-$TRAVIS_TAG
+        - tar -czf $PKGNAME.tar.gz binaryen-$TRAVIS_TAG
+        - sha256sum $PKGNAME.tar.gz > $PKGNAME.tar.gz.sha256
+      deploy:
+        provider: releases
+        api_key:
+          secret: TODO
+        file: binaryen-$TRAVIS_TAG-*.tar.gz*
+        file_glob: true
+        skip_cleanup: true
+        on:
+          tags: true
+
+    # Build binaries for other architectures using QEMU user-mode emulation.
+    # Note: We don't run tests for these architectures, because some fail under
+    # QEMU/binfmt and it takes too long time (hits time limit on Travis).
+    - <<: *build-alpine
       env: ARCH=x86
 
-    - <<: *test-alpine-no-check
+    - <<: *build-alpine
       env: ARCH=aarch64
 
-    - <<: *test-alpine-no-check
+    - <<: *build-alpine
       env: ARCH=armhf
 
-    - <<: *test-alpine-no-check
+    - <<: *build-alpine
       env: ARCH=ppc64le
 
 notifications:
